"""index_embedding_model

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-01 15:46:04.116250
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_state', sa.Column('embedding_model', sa.String(length=80), nullable=True))
    # Hasta esta migración solo existía el proveedor simulado: los índices ya creados
    # se construyeron con él.
    op.execute("UPDATE index_state SET embedding_model = 'fake:hash-v1'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_state', 'embedding_model')
    # ### end Alembic commands ###
